apiVersion: v1
kind: Service
metadata:
  name: ate-worker
  labels:
    app: ate-worker
spec:
  type: ClusterIP
  selector:
    app: ate-worker
  ports:
    - name: http
      port: 9101
      targetPort: http
